name: Nix build
on:
  pull_request: null
  push:
    branches:
      - main
    paths:
      - 'flake.nix'
      - 'web/**'
      - 'infra/**'
jobs:
  nix-build:
    permissions:
      packages: 'write'
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          install_url: https://releases.nixos.org/nix/nix-2.11.0/install

      - name: Run the FlakeHub Nix Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Write K3s config file to env
        run: |
          echo "${{ secrets.K3S_CONFIG }}" > config
          echo "KUBECONFIG=$(pwd)/config" >> "$GITHUB_ENV"

      - name: Build the blog docker file and push to registry
        run: |
          nix run .#docker-blog.copyToRegistry --no-sandbox

      - name: Build and apply k8s changes
        run: yes | nix run .#kubenix --no-sandbox

